apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /jenkins
            backend:
              serviceName: jenkins
              servicePort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  selector:
    matchLabels:
      type: master
      service: jenkins
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        type: master
        service: jenkins
    spec:
      containers:
        - name: jenkins
          image: vfarcic/jenkins
          env:
            - name: JENKINS_OPTS
              value: --prefix=/jenkins
            - name: SECRETS_DIR
              value: /etc/secrets
          volumeMounts:
            - mountPath: /var/jenkins_home
              name: jenkins-home
            - name: jenkins-creds
              mountPath: /etc/secrets
      volumes:
        - emptyDir: {}
          name: jenkins-home
        - name: jenkins-creds
          secret:
            secretName: my-creds
            defaultMode: 0444
            items:
              - key: username
                path: jenkins-user
              - key: password
                path: jenkins-pass

---

apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  ports:
    - port: 8080
  selector:
    type: master
    service: jenkins

---

kind: Secret
apiVersion: v1
metadata:
  name: my-creds
data:
  password: aW5jb2duaXRv # incognito
  username: amRvZQ==  # jdoe
type: Opaque
